export const UPDATE_BRANDS = 'UPDATE_BRANDS';
export const UPDATE_PRICES = 'UPDATE_PRICES';
export const UPDATE_SIZES = 'UPDATE_SIZES';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_SORT_PRICES = 'UPDATE_SORT_PRICES';

export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
