export const UPDATE_BRANDS = 'UPDATE_BRANDS';
export const UPDATE_PRICES = 'UPDATE_PRICES';
export const UPDATE_SIZES = 'UPDATE_SIZES';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_SORT_PRICES = 'UPDATE_SORT_PRICES';

export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';

export const BUILD_FILTER_CONFIG = 'BUILD_FILTER_CONFIG';

export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const SHOW_POPUP = 'SHOW_POPUP';
export const HIDE_POPUP = 'HIDE_POPUP';

export const UPDATE_FILTER_ROUTE = 'UPDATE_FILTER_ROUTE';
