export const UPDATE_BRANDS = "UPDATE_BRANDS";
export const UPDATE_PRICES = "UPDATE_PRICES";
export const UPDATE_SIZES = "UPDATE_SIZES";

export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const UPDATE_SORT_PRICES = "UPDATE_SORT_PRICES";
